import pg from "pg";
const { Client } = pg;

const movies = [
  { title: "Inception", description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.", poster: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg", trailer: "https://www.youtube.com/watch?v=YoHD9XEInc0", genres: ["Action","Sci-Fi","Thriller"], year: 2010, rating: 8.8, duration: "2h 28m", vipOnly: false, featured: true, watchCount: 5200 },
  { title: "The Dark Knight", description: "When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological and physical tests of heroism.", poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg", trailer: "https://www.youtube.com/watch?v=EXeTwQWrcwY", genres: ["Action","Drama","Thriller"], year: 2008, rating: 9.0, duration: "2h 32m", vipOnly: false, featured: true, watchCount: 7800 },
  { title: "Interstellar", description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity survival beyond a dying Earth.", poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", trailer: "https://www.youtube.com/watch?v=zSWdZVtXT7E", genres: ["Sci-Fi","Drama","Adventure"], year: 2014, rating: 8.6, duration: "2h 49m", vipOnly: true, featured: true, watchCount: 6100 },
  { title: "Avengers: Endgame", description: "After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos actions and restore balance to the universe.", poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg", trailer: "https://www.youtube.com/watch?v=TcMBFSGVi1c", genres: ["Action","Adventure","Sci-Fi"], year: 2019, rating: 8.4, duration: "3h 1m", vipOnly: false, featured: true, watchCount: 9200 },
  { title: "Parasite", description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.", poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", trailer: "https://www.youtube.com/watch?v=5xH0HfJHsaY", genres: ["Drama","Thriller"], year: 2019, rating: 8.5, duration: "2h 12m", vipOnly: true, featured: false, watchCount: 4300 },
  { title: "The Shawshank Redemption", description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", poster: "https://image.tmdb.org/t/p/w500/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg", trailer: "https://www.youtube.com/watch?v=6hB3S9bIaco", genres: ["Drama"], year: 1994, rating: 9.3, duration: "2h 22m", vipOnly: false, featured: false, watchCount: 8900 },
  { title: "Pulp Fiction", description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.", poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg", trailer: "https://www.youtube.com/watch?v=s7EdQ4FqbhY", genres: ["Drama","Thriller"], year: 1994, rating: 8.9, duration: "2h 34m", vipOnly: false, featured: false, watchCount: 5600 },
  { title: "The Matrix", description: "A computer programmer discovers that reality as he knows it is a simulation created by machines, and joins a rebellion to break free.", poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg", trailer: "https://www.youtube.com/watch?v=vKQi3bBA1y8", genres: ["Action","Sci-Fi"], year: 1999, rating: 8.7, duration: "2h 16m", vipOnly: false, featured: false, watchCount: 6700 },
  { title: "Joker", description: "A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain in Gotham City.", poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg", trailer: "https://www.youtube.com/watch?v=zAGVQLHvwOY", genres: ["Drama","Thriller"], year: 2019, rating: 8.4, duration: "2h 2m", vipOnly: true, featured: false, watchCount: 7100 },
  { title: "Spider-Man: No Way Home", description: "Peter Parker seeks help from Doctor Strange to restore his secret identity, but the spell goes wrong opening the multiverse.", poster: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg", trailer: "https://www.youtube.com/watch?v=JfVOs4VSpmA", genres: ["Action","Adventure","Sci-Fi"], year: 2021, rating: 8.3, duration: "2h 28m", vipOnly: false, featured: true, watchCount: 8400 },
  { title: "Get Out", description: "A young African-American man visits his white girlfriends family estate where he uncovers a deeply disturbing secret.", poster: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg", trailer: "https://www.youtube.com/watch?v=DzfpyUB60YY", genres: ["Horror","Thriller"], year: 2017, rating: 7.7, duration: "1h 44m", vipOnly: false, featured: false, watchCount: 3200 },
  { title: "Everything Everywhere All at Once", description: "A Chinese-American woman is swept up in an adventure through the multiverse where she alone can save existence.", poster: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg", trailer: "https://www.youtube.com/watch?v=wxN1T1uxQ2g", genres: ["Action","Comedy","Sci-Fi"], year: 2022, rating: 7.8, duration: "2h 19m", vipOnly: true, featured: true, watchCount: 4800 },
  { title: "La La Land", description: "A pianist and an actress fall in love in Los Angeles while attempting to reconcile their dreams for the future.", poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg", trailer: "https://www.youtube.com/watch?v=0pdqf4P9MB8", genres: ["Romance","Drama"], year: 2016, rating: 8.0, duration: "2h 8m", vipOnly: false, featured: false, watchCount: 3900 },
  { title: "Dune: Part One", description: "A noble family becomes embroiled in a war for control over the galaxys most valuable asset while its heir is troubled by visions of a dark future.", poster: "https://image.tmdb.org/t/p/w500/d5NXSklpcuveUsYXfmidOfLR3iK.jpg", trailer: "https://www.youtube.com/watch?v=8g18jFHCLXk", genres: ["Sci-Fi","Adventure","Drama"], year: 2021, rating: 8.0, duration: "2h 35m", vipOnly: true, featured: false, watchCount: 5500 },
  { title: "The Grand Budapest Hotel", description: "A writer learns of the storied past of a legendary European hotel from its owner, involving a stolen painting and a murder.", poster: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg", trailer: "https://www.youtube.com/watch?v=1Fg5iWmQjwk", genres: ["Comedy","Drama","Adventure"], year: 2014, rating: 8.1, duration: "1h 39m", vipOnly: false, featured: false, watchCount: 2800 },
  { title: "Oppenheimer", description: "The story of American scientist J. Robert Oppenheimer and his pivotal role in the development of the atomic bomb during World War II.", poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg", trailer: "https://www.youtube.com/watch?v=uYPbbksJxIg", genres: ["Drama","Thriller"], year: 2023, rating: 8.3, duration: "3h", vipOnly: true, featured: true, watchCount: 6600 },
  { title: "Knives Out", description: "A detective investigates the death of the patriarch of an eccentric, combative family in this smart whodunit mystery.", poster: "https://image.tmdb.org/t/p/w500/pThyQovXQrws2hmLinl9sskTeGn.jpg", trailer: "https://www.youtube.com/watch?v=qGqiHJTsRkQ", genres: ["Comedy","Drama","Thriller"], year: 2019, rating: 7.9, duration: "2h 10m", vipOnly: false, featured: false, watchCount: 3600 },
  { title: "Black Panther", description: "T Challa, heir to the hidden kingdom of Wakanda, must step forward to lead his people and confront a challenger from his nations past.", poster: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg", trailer: "https://www.youtube.com/watch?v=xjDjIWPwcPU", genres: ["Action","Adventure"], year: 2018, rating: 7.3, duration: "2h 14m", vipOnly: false, featured: false, watchCount: 5900 },
  { title: "Hereditary", description: "A grieving family is haunted by tragic and disturbing occurrences after the mysterious death of their secretive grandmother.", poster: "https://image.tmdb.org/t/p/w500/p9sA9XZAP39dMefdDPWsuvGFAcD.jpg", trailer: "https://www.youtube.com/watch?v=V6wWKNij_1M", genres: ["Horror","Drama"], year: 2018, rating: 7.3, duration: "2h 7m", vipOnly: false, featured: false, watchCount: 2400 },
  { title: "Soul", description: "A musician transported out of his body must find his way back with the help of an infant soul learning what life is really about.", poster: "https://image.tmdb.org/t/p/w500/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg", trailer: "https://www.youtube.com/watch?v=xOsLIiBStEs", genres: ["Animation","Comedy","Drama"], year: 2020, rating: 8.0, duration: "1h 40m", vipOnly: false, featured: false, watchCount: 4100 },
];

const client = new Client({ connectionString: process.env.DATABASE_URL });
await client.connect();
let inserted = 0, skipped = 0;
for (const m of movies) {
  const r = await client.query(
    `INSERT INTO movies (title,description,poster,trailer,streaming_links,download_links,genres,year,rating,duration,vip_only,featured,watch_count)
     VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
     ON CONFLICT DO NOTHING RETURNING id`,
    [m.title,m.description,m.poster,m.trailer,[],[],m.genres,m.year,m.rating,m.duration,m.vipOnly,m.featured,m.watchCount]
  );
  if (r.rows.length) { inserted++; console.log("  + " + m.title); }
  else { skipped++; console.log("  ~ " + m.title + " (already exists)"); }
}
await client.end();
console.log(`\nDone — ${inserted} inserted, ${skipped} skipped.`);
