import { db, moviesTable, bannersTable } from "@workspace/db";

const movies = [
  // ACTION
  { title: "Inception", description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.", poster: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg", trailer: "https://www.youtube.com/watch?v=YoHD9XEInc0", genres: ["Action","Sci-Fi","Thriller"], year: 2010, rating: 8.8, duration: "2h 28m", vipOnly: false, featured: true, watchCount: 5200 },
  { title: "The Dark Knight", description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of heroism.", poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg", trailer: "https://www.youtube.com/watch?v=EXeTwQWrcwY", genres: ["Action","Crime","Drama"], year: 2008, rating: 9.0, duration: "2h 32m", vipOnly: false, featured: true, watchCount: 7800 },
  { title: "Mad Max: Fury Road", description: "In a post-apocalyptic wasteland, Max teams up with Furiosa to flee from a tyrant who controls the desert's water supply.", poster: "https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg", trailer: "https://www.youtube.com/watch?v=hEJnMQG9ev8", genres: ["Action","Adventure","Sci-Fi"], year: 2015, rating: 8.1, duration: "2h 0m", vipOnly: false, featured: false, watchCount: 4900 },
  { title: "John Wick", description: "An ex-hitman comes out of retirement to track down the gangsters that killed his dog, a gift from his recently deceased wife.", poster: "https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg", trailer: "https://www.youtube.com/watch?v=2AUmvWm5ZDQ", genres: ["Action","Crime","Thriller"], year: 2014, rating: 7.4, duration: "1h 41m", vipOnly: false, featured: false, watchCount: 4100 },
  { title: "Top Gun: Maverick", description: "After more than thirty years of service as one of the Navy's top aviators, Pete Mitchell is called upon to train a detachment of graduates for a specialized mission.", poster: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg", trailer: "https://www.youtube.com/watch?v=giXco2jaZ_4", genres: ["Action","Drama"], year: 2022, rating: 8.3, duration: "2h 10m", vipOnly: false, featured: true, watchCount: 6800 },
  // SCI-FI
  { title: "Interstellar", description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival beyond a dying Earth.", poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", trailer: "https://www.youtube.com/watch?v=zSWdZVtXT7E", genres: ["Sci-Fi","Drama","Adventure"], year: 2014, rating: 8.6, duration: "2h 49m", vipOnly: true, featured: true, watchCount: 6100 },
  { title: "Dune: Part One", description: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future.", poster: "https://image.tmdb.org/t/p/w500/d5NXSklpcKDQbM6nFKHVkj3HFJo.jpg", trailer: "https://www.youtube.com/watch?v=8g18jFHCLXk", genres: ["Sci-Fi","Adventure","Drama"], year: 2021, rating: 8.0, duration: "2h 35m", vipOnly: false, featured: true, watchCount: 5500 },
  { title: "The Matrix", description: "A computer programmer discovers that reality as he knows it is a simulation created by machines, and joins a rebellion to break free.", poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg", trailer: "https://www.youtube.com/watch?v=vKQi3bBA1y8", genres: ["Action","Sci-Fi"], year: 1999, rating: 8.7, duration: "2h 16m", vipOnly: false, featured: false, watchCount: 6700 },
  { title: "Arrival", description: "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.", poster: "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg", trailer: "https://www.youtube.com/watch?v=tFMo3UJ4B4g", genres: ["Sci-Fi","Drama","Mystery"], year: 2016, rating: 7.9, duration: "1h 56m", vipOnly: true, featured: false, watchCount: 3400 },
  { title: "Blade Runner 2049", description: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.", poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg", trailer: "https://www.youtube.com/watch?v=haAVnX8NNHM", genres: ["Sci-Fi","Drama","Mystery"], year: 2017, rating: 8.0, duration: "2h 44m", vipOnly: true, featured: false, watchCount: 3800 },
  { title: "Tenet", description: "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage.", poster: "https://image.tmdb.org/t/p/w500/k68nPLbIST6NP96JmTxmZijOneM.jpg", trailer: "https://www.youtube.com/watch?v=LdOM0x0XDMo", genres: ["Action","Sci-Fi","Thriller"], year: 2020, rating: 7.3, duration: "2h 30m", vipOnly: true, featured: false, watchCount: 3200 },
  // DRAMA
  { title: "The Shawshank Redemption", description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", poster: "https://image.tmdb.org/t/p/w500/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg", trailer: "https://www.youtube.com/watch?v=6hB3S9bIaco", genres: ["Drama","Crime"], year: 1994, rating: 9.3, duration: "2h 22m", vipOnly: false, featured: false, watchCount: 8900 },
  { title: "Parasite", description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.", poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", trailer: "https://www.youtube.com/watch?v=5xH0HfJHsaY", genres: ["Drama","Thriller","Comedy"], year: 2019, rating: 8.5, duration: "2h 12m", vipOnly: false, featured: false, watchCount: 4300 },
  { title: "Oppenheimer", description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.", poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg", trailer: "https://www.youtube.com/watch?v=uYPbbksJxIg", genres: ["Drama","History","Thriller"], year: 2023, rating: 8.5, duration: "3h 0m", vipOnly: false, featured: true, watchCount: 6600 },
  { title: "The Godfather", description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant youngest son.", poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLLeHeYVqdF.jpg", trailer: "https://www.youtube.com/watch?v=sY1S34973zA", genres: ["Drama","Crime"], year: 1972, rating: 9.2, duration: "2h 55m", vipOnly: false, featured: false, watchCount: 7500 },
  { title: "1917", description: "Two British soldiers must cross enemy territory and deliver a message that could save 1,600 men from a deadly ambush.", poster: "https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYFLCCrMi9.jpg", trailer: "https://www.youtube.com/watch?v=YqNYrYUiMfg", genres: ["Drama","War","Action"], year: 2019, rating: 8.3, duration: "1h 59m", vipOnly: false, featured: false, watchCount: 4700 },
  { title: "The Revenant", description: "A frontiersman on a fur trading expedition in the 1820s fights for survival after being left for dead by members of his own hunting team.", poster: "https://image.tmdb.org/t/p/w500/ji3ecJphATlVgZhVIt9fnEENTKw.jpg", trailer: "https://www.youtube.com/watch?v=LoebZZ8K5N0", genres: ["Adventure","Drama","Thriller"], year: 2015, rating: 8.0, duration: "2h 36m", vipOnly: false, featured: false, watchCount: 4200 },
  { title: "Pulp Fiction", description: "The lives of two mob hitmen, a boxer, a gangster, and his wife intertwine in four tales of violence and redemption.", poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg", trailer: "https://www.youtube.com/watch?v=s7EdQ4FqbhY", genres: ["Drama","Crime","Thriller"], year: 1994, rating: 8.9, duration: "2h 34m", vipOnly: false, featured: false, watchCount: 5600 },
  // HORROR / THRILLER
  { title: "Get Out", description: "A young African-American man visits his white girlfriend's family estate where he gradually uncovers a disturbing secret.", poster: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg", trailer: "https://www.youtube.com/watch?v=DzfpyUB60YY", genres: ["Horror","Mystery","Thriller"], year: 2017, rating: 7.7, duration: "1h 44m", vipOnly: false, featured: false, watchCount: 3200 },
  { title: "Hereditary", description: "A grieving family is haunted by tragic and disturbing occurrences after the mysterious death of their secretive grandmother.", poster: "https://image.tmdb.org/t/p/w500/p9FFlxm7y3u2sMm2b8Cb42EEMQL.jpg", trailer: "https://www.youtube.com/watch?v=V6wWKNij_1M", genres: ["Horror","Drama","Mystery"], year: 2018, rating: 7.3, duration: "2h 7m", vipOnly: true, featured: false, watchCount: 2400 },
  { title: "A Quiet Place", description: "In a post-apocalyptic world, a family is forced to live in near silence while hiding from creatures that hunt by sound.", poster: "https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg", trailer: "https://www.youtube.com/watch?v=WR7cc5t7tv8", genres: ["Horror","Drama","Sci-Fi"], year: 2018, rating: 7.5, duration: "1h 30m", vipOnly: false, featured: false, watchCount: 3500 },
  { title: "Midsommar", description: "A couple travels to Sweden to visit a rural hometown's midsummer festival. What begins as an idyllic retreat quickly devolves into a violent ordeal.", poster: "https://image.tmdb.org/t/p/w500/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg", trailer: "https://www.youtube.com/watch?v=1Erk41CYzQ8", genres: ["Horror","Drama","Mystery"], year: 2019, rating: 7.1, duration: "2h 28m", vipOnly: true, featured: false, watchCount: 2100 },
  { title: "Gone Girl", description: "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight and pressure of the investigation turn on him.", poster: "https://image.tmdb.org/t/p/w500/pMIixvHwsM2atMNUHZmCiTBRiV5.jpg", trailer: "https://www.youtube.com/watch?v=2-UHIkS_EUT", genres: ["Drama","Mystery","Thriller"], year: 2014, rating: 8.1, duration: "2h 29m", vipOnly: false, featured: false, watchCount: 4000 },
  { title: "Prisoners", description: "When Keller Dover's daughter and her friend go missing, he takes matters into his own hands as the police detective works the case.", poster: "https://image.tmdb.org/t/p/w500/oEmmEMzIBkAUfYWGkJVBSzMhDw.jpg", trailer: "https://www.youtube.com/watch?v=Vt9vl8iAN3Q", genres: ["Crime","Drama","Thriller"], year: 2013, rating: 8.1, duration: "2h 33m", vipOnly: false, featured: false, watchCount: 3800 },
  // COMEDY
  { title: "The Grand Budapest Hotel", description: "A writer encounters the owner of an aging European hotel between the wars who tells him of his early years as a lobby boy.", poster: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg", trailer: "https://www.youtube.com/watch?v=1Fg5iWmQjwk", genres: ["Comedy","Drama","Adventure"], year: 2014, rating: 8.1, duration: "1h 39m", vipOnly: false, featured: false, watchCount: 2800 },
  { title: "Knives Out", description: "A detective investigates the death of a patriarch of an eccentric, combative family in this smart and twisty whodunit.", poster: "https://image.tmdb.org/t/p/w500/pThyQovXQrws2Q07t16hjKuJGvZ.jpg", trailer: "https://www.youtube.com/watch?v=qGqiHJTsRkQ", genres: ["Comedy","Crime","Drama"], year: 2019, rating: 7.9, duration: "2h 10m", vipOnly: false, featured: false, watchCount: 3600 },
  { title: "Everything Everywhere All at Once", description: "An aging Chinese immigrant is swept up in an insane adventure where she alone can save existence by connecting with the lives she could have led.", poster: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg", trailer: "https://www.youtube.com/watch?v=wxN1T1uxQ2g", genres: ["Comedy","Sci-Fi","Action"], year: 2022, rating: 7.8, duration: "2h 19m", vipOnly: false, featured: true, watchCount: 4800 },
  // ANIMATION
  { title: "Spirited Away", description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.", poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg", trailer: "https://www.youtube.com/watch?v=ByXuk9QqQkk", genres: ["Animation","Adventure","Fantasy"], year: 2001, rating: 8.6, duration: "2h 4m", vipOnly: false, featured: false, watchCount: 5100 },
  { title: "Spider-Man: Into the Spider-Verse", description: "Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions to stop a threat.", poster: "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg", trailer: "https://www.youtube.com/watch?v=tg52up16eq0", genres: ["Animation","Action","Adventure"], year: 2018, rating: 8.4, duration: "1h 57m", vipOnly: false, featured: false, watchCount: 4600 },
  { title: "Soul", description: "A musician who has lost his passion for music is transported out of his body and must find his way back with the help of an infant soul learning what life is all about.", poster: "https://image.tmdb.org/t/p/w500/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg", trailer: "https://www.youtube.com/watch?v=xOsLIiBStEs", genres: ["Animation","Comedy","Drama"], year: 2020, rating: 8.0, duration: "1h 40m", vipOnly: false, featured: false, watchCount: 4100 },
  // ROMANCE
  { title: "La La Land", description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.", poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg", trailer: "https://www.youtube.com/watch?v=0pdqf4P9MB8", genres: ["Drama","Romance","Music"], year: 2016, rating: 8.0, duration: "2h 8m", vipOnly: false, featured: false, watchCount: 3900 },
  { title: "Past Lives", description: "Nora and Hae Sung, two deeply connected childhood friends, are separated when Nora's family emigrates. Twenty-four years later, they are reunited in New York.", poster: "https://image.tmdb.org/t/p/w500/k3waqVXSnQMIscCFInfnS1UMpNd.jpg", trailer: "https://www.youtube.com/watch?v=oLBBkWL5i8k", genres: ["Drama","Romance"], year: 2023, rating: 7.9, duration: "1h 46m", vipOnly: true, featured: false, watchCount: 2200 },
  // SUPERHERO / ADVENTURE
  { title: "Spider-Man: No Way Home", description: "Peter Parker seeks help from Doctor Strange to restore his secret identity, but the spell goes wrong, opening the multiverse to dangerous enemies.", poster: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg", trailer: "https://www.youtube.com/watch?v=JfVOs4VSpmA", genres: ["Action","Adventure","Sci-Fi"], year: 2021, rating: 8.2, duration: "2h 28m", vipOnly: false, featured: false, watchCount: 8400 },
  { title: "Avengers: Endgame", description: "After the devastating events of Infinity War, the universe is in ruins. The Avengers assemble once more to reverse Thanos's actions and restore balance to the universe.", poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg", trailer: "https://www.youtube.com/watch?v=TcMBFSGVi1c", genres: ["Action","Adventure","Sci-Fi"], year: 2019, rating: 8.4, duration: "3h 1m", vipOnly: false, featured: true, watchCount: 9200 },
  { title: "Joker", description: "A mentally troubled stand-up comedian embarks on a downward spiral leading to the creation of one of DC's most iconic villains in Gotham City.", poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg", trailer: "https://www.youtube.com/watch?v=zAGVQLHvwOY", genres: ["Drama","Crime","Thriller"], year: 2019, rating: 8.4, duration: "2h 2m", vipOnly: true, featured: false, watchCount: 7100 },
  { title: "Black Panther", description: "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and confront a challenger from his nation's past.", poster: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg", trailer: "https://www.youtube.com/watch?v=xjDjIWPwcPU", genres: ["Action","Adventure","Sci-Fi"], year: 2018, rating: 7.3, duration: "2h 14m", vipOnly: false, featured: false, watchCount: 5900 },
  { title: "Avatar: The Way of Water", description: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. A familiar threat returns to finish what was previously started.", poster: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg", trailer: "https://www.youtube.com/watch?v=d9MyW72ELq0", genres: ["Sci-Fi","Adventure","Action"], year: 2022, rating: 7.6, duration: "3h 12m", vipOnly: false, featured: true, watchCount: 6300 },
];

const banners = [
  { title: "Dune: Part Two", subtitle: "The saga continues. Paul Atreides unites with the Fremen to wage war against the Harkonnens.", image: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg", ctaText: "Watch Now", ctaLink: "/movies", active: true, orderIndex: 0 },
  { title: "Oppenheimer", subtitle: "The world forever changed. Experience Christopher Nolan's epic masterpiece.", image: "https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg", ctaText: "Watch Now", ctaLink: "/movies", active: true, orderIndex: 1 },
  { title: "Top Gun: Maverick", subtitle: "Feel the need for speed. The legend returns.", image: "https://image.tmdb.org/t/p/original/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg", ctaText: "Watch Now", ctaLink: "/movies", active: true, orderIndex: 2 },
  { title: "Everything Everywhere All at Once", subtitle: "Winner of 7 Academy Awards. A mind-bending multiverse adventure like nothing you've seen.", image: "https://image.tmdb.org/t/p/original/ss0Os3uWJfQAENILHZUdX8Tt1OC.jpg", ctaText: "Watch Now", ctaLink: "/movies", active: true, orderIndex: 3 },
  { title: "Avengers: Endgame", subtitle: "Whatever it takes. The most ambitious crossover event in history.", image: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg", ctaText: "Watch Now", ctaLink: "/movies", active: true, orderIndex: 4 },
  { title: "Spider-Man: No Way Home", subtitle: "The multiverse is open. All variants converge.", image: "https://image.tmdb.org/t/p/original/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg", ctaText: "Watch Now", ctaLink: "/movies", active: true, orderIndex: 5 },
  { title: "Interstellar — VIP Exclusive", subtitle: "Beyond the stars. An odyssey through time and space. Exclusive to VIP members.", image: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg", ctaText: "Go VIP", ctaLink: "/vip", active: true, orderIndex: 6 },
];

async function seed() {
  console.log("🎬 Seeding movies...");
  for (const movie of movies) {
    await db.insert(moviesTable).values(movie).onConflictDoNothing();
    console.log(`  ✓ ${movie.title}`);
  }

  console.log("\n🖼️  Seeding banners...");
  for (const banner of banners) {
    await db.insert(bannersTable).values(banner).onConflictDoNothing();
    console.log(`  ✓ ${banner.title}`);
  }

  console.log(`\n✅ Seed complete — ${movies.length} movies, ${banners.length} banners`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
