import { db, moviesTable, bannersTable } from "@workspace/db";

const movies = [
  // Action
  {
    title: "Inception",
    description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    poster: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    genres: ["Action", "Sci-Fi", "Thriller"],
    year: 2010,
    rating: 8.8,
    duration: "2h 28m",
    vipOnly: false,
    featured: true,
  },
  {
    title: "The Dark Knight",
    description: "Batman raises the stakes in his war on crime with the help of Lieutenant Jim Gordon and District Attorney Harvey Dent.",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    genres: ["Action", "Crime", "Drama"],
    year: 2008,
    rating: 9.0,
    duration: "2h 32m",
    vipOnly: false,
    featured: true,
  },
  {
    title: "Mad Max: Fury Road",
    description: "In a post-apocalyptic wasteland, Max teams up with Furiosa to flee from a tyrant who controls the desert's water supply.",
    poster: "https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
    genres: ["Action", "Adventure", "Sci-Fi"],
    year: 2015,
    rating: 8.1,
    duration: "2h 0m",
    vipOnly: false,
    featured: false,
  },
  {
    title: "John Wick",
    description: "An ex-hitman comes out of retirement to track down the gangsters that killed his dog, a gift from his recently deceased wife.",
    poster: "https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
    genres: ["Action", "Crime", "Thriller"],
    year: 2014,
    rating: 7.4,
    duration: "1h 41m",
    vipOnly: false,
    featured: false,
  },
  {
    title: "Top Gun: Maverick",
    description: "After more than thirty years of service as one of the Navy's top aviators, Maverick is called upon to train a detachment of graduates.",
    poster: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    genres: ["Action", "Drama"],
    year: 2022,
    rating: 8.3,
    duration: "2h 10m",
    vipOnly: false,
    featured: true,
  },
  // Sci-Fi
  {
    title: "Interstellar",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    genres: ["Sci-Fi", "Drama", "Adventure"],
    year: 2014,
    rating: 8.6,
    duration: "2h 49m",
    vipOnly: true,
    featured: true,
  },
  {
    title: "Dune",
    description: "Paul Atreides leads nomadic tribes in a revolt against a galactic emperor who controls the most precious resource in the universe.",
    poster: "https://image.tmdb.org/t/p/w500/d5NXSklpcKDQbM6nFKHVkj3HFJo.jpg",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    year: 2021,
    rating: 8.0,
    duration: "2h 35m",
    vipOnly: false,
    featured: true,
  },
  {
    title: "The Matrix",
    description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    genres: ["Sci-Fi", "Action"],
    year: 1999,
    rating: 8.7,
    duration: "2h 16m",
    vipOnly: false,
    featured: false,
  },
  {
    title: "Arrival",
    description: "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
    poster: "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
    genres: ["Sci-Fi", "Drama", "Mystery"],
    year: 2016,
    rating: 7.9,
    duration: "1h 56m",
    vipOnly: true,
    featured: false,
  },
  {
    title: "Blade Runner 2049",
    description: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard.",
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    genres: ["Sci-Fi", "Drama", "Mystery"],
    year: 2017,
    rating: 8.0,
    duration: "2h 44m",
    vipOnly: true,
    featured: false,
  },
  // Drama
  {
    title: "The Shawshank Redemption",
    description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    poster: "https://image.tmdb.org/t/p/w500/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
    genres: ["Drama", "Crime"],
    year: 1994,
    rating: 9.3,
    duration: "2h 22m",
    vipOnly: false,
    featured: false,
  },
  {
    title: "Parasite",
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    genres: ["Drama", "Thriller", "Comedy"],
    year: 2019,
    rating: 8.5,
    duration: "2h 12m",
    vipOnly: false,
    featured: false,
  },
  {
    title: "Oppenheimer",
    description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    genres: ["Drama", "History", "Thriller"],
    year: 2023,
    rating: 8.5,
    duration: "3h 0m",
    vipOnly: false,
    featured: true,
  },
  {
    title: "The Godfather",
    description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant youngest son.",
    poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLLeHeYVqdF.jpg",
    genres: ["Drama", "Crime"],
    year: 1972,
    rating: 9.2,
    duration: "2h 55m",
    vipOnly: false,
    featured: false,
  },
  {
    title: "1917",
    description: "Two British soldiers must cross enemy territory to deliver a message that could save 1,600 men from a deadly ambush.",
    poster: "https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
    genres: ["Drama", "War", "Action"],
    year: 2019,
    rating: 8.3,
    duration: "1h 59m",
    vipOnly: false,
    featured: false,
  },
  // Horror / Thriller
  {
    title: "Get Out",
    description: "A young African-American visits his white girlfriend's family estate and becomes ensnared in a more sinister real reason for the invitation.",
    poster: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    genres: ["Horror", "Mystery", "Thriller"],
    year: 2017,
    rating: 7.7,
    duration: "1h 44m",
    vipOnly: false,
    featured: false,
  },
  {
    title: "Hereditary",
    description: "A grieving family is haunted by tragic and disturbing occurrences after the death of their secretive grandmother.",
    poster: "https://image.tmdb.org/t/p/w500/p9FFlxm7y3u2sMm2b8Cb42EEMQL.jpg",
    genres: ["Horror", "Drama", "Mystery"],
    year: 2018,
    rating: 7.3,
    duration: "2h 7m",
    vipOnly: true,
    featured: false,
  },
  {
    title: "A Quiet Place",
    description: "In a post-apocalyptic world, a family is forced to live in near silence while hiding from monsters that hunt by sound.",
    poster: "https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
    genres: ["Horror", "Drama", "Sci-Fi"],
    year: 2018,
    rating: 7.5,
    duration: "1h 30m",
    vipOnly: false,
    featured: false,
  },
  {
    title: "Midsommar",
    description: "A couple travels to Sweden to visit a rural hometown's fabled midsummer festival. What begins as an idyllic retreat quickly devolves into an increasingly violent ordeal.",
    poster: "https://image.tmdb.org/t/p/w500/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
    genres: ["Horror", "Drama", "Mystery"],
    year: 2019,
    rating: 7.1,
    duration: "2h 28m",
    vipOnly: true,
    featured: false,
  },
  // Comedy
  {
    title: "The Grand Budapest Hotel",
    description: "A writer encounters the owner of an aging European hotel between the wars who tells him of his early years serving as a lobby boy.",
    poster: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    genres: ["Comedy", "Drama", "Adventure"],
    year: 2014,
    rating: 8.1,
    duration: "1h 39m",
    vipOnly: false,
    featured: false,
  },
  {
    title: "Knives Out",
    description: "A detective investigates the death of a patriarch of an eccentric, combative family.",
    poster: "https://image.tmdb.org/t/p/w500/pThyQovXQrws2Q07t16hjKuJGvZ.jpg",
    genres: ["Comedy", "Crime", "Drama"],
    year: 2019,
    rating: 7.9,
    duration: "2h 10m",
    vipOnly: false,
    featured: false,
  },
  {
    title: "Everything Everywhere All at Once",
    description: "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led.",
    poster: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    genres: ["Comedy", "Sci-Fi", "Action"],
    year: 2022,
    rating: 7.8,
    duration: "2h 19m",
    vipOnly: false,
    featured: true,
  },
  // Adventure / Fantasy
  {
    title: "Avatar: The Way of Water",
    description: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. A familiar threat returns to finish what was previously started.",
    poster: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    genres: ["Sci-Fi", "Adventure", "Action"],
    year: 2022,
    rating: 7.6,
    duration: "3h 12m",
    vipOnly: false,
    featured: true,
  },
  {
    title: "Doctor Strange in the Multiverse of Madness",
    description: "Doctor Strange teams up with a mysterious newcomer who has the ability to travel between multiverses.",
    poster: "https://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
    genres: ["Action", "Adventure", "Fantasy"],
    year: 2022,
    rating: 6.9,
    duration: "2h 6m",
    vipOnly: false,
    featured: false,
  },
  {
    title: "Black Panther: Wakanda Forever",
    description: "The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King T'Challa.",
    poster: "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    genres: ["Action", "Adventure", "Drama"],
    year: 2022,
    rating: 6.7,
    duration: "2h 41m",
    vipOnly: false,
    featured: false,
  },
  {
    title: "Spider-Man: No Way Home",
    description: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear.",
    poster: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    genres: ["Action", "Adventure", "Sci-Fi"],
    year: 2021,
    rating: 8.2,
    duration: "2h 28m",
    vipOnly: false,
    featured: false,
  },
  // Animation
  {
    title: "Spirited Away",
    description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
    poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    genres: ["Animation", "Adventure", "Fantasy"],
    year: 2001,
    rating: 8.6,
    duration: "2h 4m",
    vipOnly: false,
    featured: false,
  },
  {
    title: "Spider-Man: Into the Spider-Verse",
    description: "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat.",
    poster: "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    genres: ["Animation", "Action", "Adventure"],
    year: 2018,
    rating: 8.4,
    duration: "1h 57m",
    vipOnly: false,
    featured: false,
  },
  // Romance
  {
    title: "La La Land",
    description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    genres: ["Drama", "Romance", "Music"],
    year: 2016,
    rating: 8.0,
    duration: "2h 8m",
    vipOnly: false,
    featured: false,
  },
  {
    title: "Past Lives",
    description: "Nora and Hae Sung, two deeply connected childhood friends, are separated when Nora's family emigrates from South Korea. 24 years later, they meet in New York.",
    poster: "https://image.tmdb.org/t/p/w500/k3waqVXSnQMIscCFInfnS1UMpNd.jpg",
    genres: ["Drama", "Romance"],
    year: 2023,
    rating: 7.9,
    duration: "1h 46m",
    vipOnly: true,
    featured: false,
  },
  // Thriller / Crime
  {
    title: "Prisoners",
    description: "When Keller Dover's daughter and her friend go missing, he takes matters into his own hands as the police detective works the case.",
    poster: "https://image.tmdb.org/t/p/w500/oEmmEMzIBkAUfYWGkJVBSzMhDw.jpg",
    genres: ["Crime", "Drama", "Thriller"],
    year: 2013,
    rating: 8.1,
    duration: "2h 33m",
    vipOnly: false,
    featured: false,
  },
  {
    title: "Gone Girl",
    description: "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight and pressure of the investigation turn on him.",
    poster: "https://image.tmdb.org/t/p/w500/pMIixvHwsM2atMNUHZmCiTBRiV5.jpg",
    genres: ["Drama", "Mystery", "Thriller"],
    year: 2014,
    rating: 8.1,
    duration: "2h 29m",
    vipOnly: false,
    featured: false,
  },
  {
    title: "Tenet",
    description: "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage.",
    poster: "https://image.tmdb.org/t/p/w500/k68nPLbIST6NP96JmTxmZijOneM.jpg",
    genres: ["Action", "Sci-Fi", "Thriller"],
    year: 2020,
    rating: 7.3,
    duration: "2h 30m",
    vipOnly: true,
    featured: false,
  },
  {
    title: "The Revenant",
    description: "A frontiersman on a fur trading expedition in the 1820s fights for survival after being left for dead by members of his own hunting team.",
    poster: "https://image.tmdb.org/t/p/w500/ji3ecJphATlVgZhVIt9fnEENTKw.jpg",
    genres: ["Adventure", "Drama", "Thriller"],
    year: 2015,
    rating: 8.0,
    duration: "2h 36m",
    vipOnly: false,
    featured: false,
  },
];

const banners = [
  {
    title: "Dune: Part Two",
    subtitle: "The saga continues. Paul Atreides unites with the Fremen to wage war on Harkonnen.",
    image: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    ctaText: "Watch Now",
    ctaLink: "/movies",
    active: true,
    orderIndex: 0,
  },
  {
    title: "Oppenheimer",
    subtitle: "The world forever changed. Experience Christopher Nolan's epic masterpiece.",
    image: "https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
    ctaText: "Watch Now",
    ctaLink: "/movies",
    active: true,
    orderIndex: 1,
  },
  {
    title: "Inception",
    subtitle: "Your mind is the scene of the crime. Enter the dream.",
    image: "https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    ctaText: "Watch Now",
    ctaLink: "/movies",
    active: true,
    orderIndex: 2,
  },
  {
    title: "Top Gun: Maverick",
    subtitle: "Feel the need for speed. The legend returns.",
    image: "https://image.tmdb.org/t/p/original/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
    ctaText: "Watch Now",
    ctaLink: "/movies",
    active: true,
    orderIndex: 3,
  },
  {
    title: "Everything Everywhere All at Once",
    subtitle: "A mind-bending multiverse adventure. Winner of 7 Academy Awards.",
    image: "https://image.tmdb.org/t/p/original/ss0Os3uWJfQAENILHZUdX8Tt1OC.jpg",
    ctaText: "Watch Now",
    ctaLink: "/movies",
    active: true,
    orderIndex: 4,
  },
  {
    title: "Spider-Man: No Way Home",
    subtitle: "The multiverse is open. All variants converge.",
    image: "https://image.tmdb.org/t/p/original/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
    ctaText: "Watch Now",
    ctaLink: "/movies",
    active: true,
    orderIndex: 5,
  },
  {
    title: "Interstellar — VIP Exclusive",
    subtitle: "Beyond the stars. An odyssey through time and space. Available for VIP members.",
    image: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    ctaText: "Go VIP",
    ctaLink: "/vip",
    active: true,
    orderIndex: 6,
  },
];

async function seed() {
  console.log("Seeding movies...");
  await db.insert(moviesTable).values(movies).onConflictDoNothing();
  console.log(`✅ Inserted ${movies.length} movies`);

  console.log("Seeding banners...");
  await db.insert(bannersTable).values(banners).onConflictDoNothing();
  console.log(`✅ Inserted ${banners.length} banners`);

  console.log("✅ Seed complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
